### ISSUE TITLE
Tip Calculator Sample for iOS Bootcamp

### ISSUE THREAD

**Issue by niazjalal** [niazjalal/ios_bootcamp_tipcalculator#1]
Here is the initial Tip Calculator Sample for review!  Currently working on settings view.

@thecodepath
@timothy1ee

**Comment by timothy1ee** [comment]
Great, can you pick a 15 minute slot here: https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg

The next slots are this coming Thursday and Friday. Once you've picked a slot, can you edit it with your phone number?

Also, comment in this issue when the settings view is complete.

**Comment by niazjalal** [comment]
Thanks.  I have signed up for the 10:15-10:30am on Friday slot.  Also the settings view is complete.  I can be reached at 408.637.1262 (also in the calendar).  Look forward to speaking with you.

**Comment by niazjalal** [comment]
Completed.
